# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30dc0016344a54752cc193e615e33c48eb1e57245cbdcac3c8bf37cfc337ce8984e2062182c6c3089b4a7661791c20d84ab2a757c0c4b5b961b43a9de6391e24
  forecast_api_key: 898455ff440a4a55ab612e9f3ae47daf

test:
  secret_key_base: a4074704b3b90f69bb89f71805262f9b8c5e05d37166480681e374e7b2d4f5841968ad0790f8f88e638fddb9b7eba0bd043d134f9ed52c2ddcdcf82bdf0c6330

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  forecast_api_key: <%= ENV["FORECAST_API_KEY"] %>
